  ------------------------------------------------------------------------

  ------------------------------------------------------------------------

               15:49 26/01/00: Page 1 (HHH) COURTS Pinochet MP
  ------------------------------------------------------------------------
TORY MP PROTESTS OVER BELGIAN `INTERFERENCE' IN PINOCHET CASE<
By Chris Moncrieff, PA News<
Tory MP Gerald Howarth said today he would lodge a formal protest to the
Belgian Embassy over Belgium's ``offensive interference'' in the Augusto
Pinochet affair.<
Belgium is applying in the High Court for permission to seek a judicial review
of the Government's ``failure'' to assure the Belgian authorities that Pinochet
would not be sent home before Britain had complied with its international legal
obligations to co-operate with other countries wanting to extradite the former
dictator.<
Mr Howarth, MP for Aldershot, said: ``It is one thing for the Government of
Spain to express an interest in these matters. But I find it completely
offensive for the Government of Belgium to challenge the Home Secretary, Jack
Straw, in our courts over his handling of a domestic British matter, namely the
medical examination of the former head of state.<
``This seems to me to be wholly contrary to the spirit of being a good
European. The Belgians should have no right whatsoever to seek to interfere in a
matter which is entirely within the province of the British Government.''<
end
